---
id: boot2docker-upgrade
base_name: boot2docker-upgrade
tags:
- docker
- boot2docker
presentation_date: 2014.11.14
version: 1.0.0
licenses: []
slideshare_id: boot2docker-upgrade
speaker_deck_id: boot2docker-upgrade
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :rd
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
